from exceptions_1.excercises import task_1

def main():
    print('start app')

    task_1()

    print('finish')

if __name__ == "__main__":
    main()
